name: "Production Deployment"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: "Terraform Production Deployment"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.0

      - name: Terraform Init (Dev)
        working-directory: ./terraform/dev
        run: terraform init

      - name: Destroy Preview Terraform Deployment
        working-directory: ./terraform/dev
        run: |
          if terraform workspace list | grep -q "pr${{ github.event.number }}"; then
            terraform workspace select pr${{ github.event.number }}
            terraform destroy -auto-approve -no-color
            terraform workspace select default
            terraform workspace delete pr${{ github.event.number }}
          fi

      - name: Terraform Init (Release)
        working-directory: ./terraform/release
        run: terraform init

      - name: Terraform Apply
        id: apply
        working-directory: ./terraform/release
        run: terraform apply -auto-approve -no-color

      - name: Publish Results to Step Summary
        if: always()
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          # Terraform Production Deployment

          <details open>
          <summary>Terraform Apply: ${{ steps.apply.outcome == 'success' && '✅ Passed' || '❌ Failed' }}</summary>

          \`\`\`
          ${{ steps.apply.outputs.stdout }}
          \`\`\`

          </details>
          EOF
